// Code generated by ent, DO NOT EDIT.

package alibabacode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/espitman/jbm-hr-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldCode, v))
}

// Used applies equality check predicate on the "used" field. It's identical to UsedEQ.
func Used(v bool) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldUsed, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldCreatedAt, v))
}

// AssignToUserID applies equality check predicate on the "assign_to_user_id" field. It's identical to AssignToUserIDEQ.
func AssignToUserID(v int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldAssignToUserID, v))
}

// AssignAt applies equality check predicate on the "assign_at" field. It's identical to AssignAtEQ.
func AssignAt(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldAssignAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldContainsFold(FieldCode, v))
}

// UsedEQ applies the EQ predicate on the "used" field.
func UsedEQ(v bool) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldUsed, v))
}

// UsedNEQ applies the NEQ predicate on the "used" field.
func UsedNEQ(v bool) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNEQ(FieldUsed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldLTE(FieldCreatedAt, v))
}

// AssignToUserIDEQ applies the EQ predicate on the "assign_to_user_id" field.
func AssignToUserIDEQ(v int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldAssignToUserID, v))
}

// AssignToUserIDNEQ applies the NEQ predicate on the "assign_to_user_id" field.
func AssignToUserIDNEQ(v int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNEQ(FieldAssignToUserID, v))
}

// AssignToUserIDIn applies the In predicate on the "assign_to_user_id" field.
func AssignToUserIDIn(vs ...int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldIn(FieldAssignToUserID, vs...))
}

// AssignToUserIDNotIn applies the NotIn predicate on the "assign_to_user_id" field.
func AssignToUserIDNotIn(vs ...int) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNotIn(FieldAssignToUserID, vs...))
}

// AssignToUserIDIsNil applies the IsNil predicate on the "assign_to_user_id" field.
func AssignToUserIDIsNil() predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldIsNull(FieldAssignToUserID))
}

// AssignToUserIDNotNil applies the NotNil predicate on the "assign_to_user_id" field.
func AssignToUserIDNotNil() predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNotNull(FieldAssignToUserID))
}

// AssignAtEQ applies the EQ predicate on the "assign_at" field.
func AssignAtEQ(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldAssignAt, v))
}

// AssignAtNEQ applies the NEQ predicate on the "assign_at" field.
func AssignAtNEQ(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNEQ(FieldAssignAt, v))
}

// AssignAtIn applies the In predicate on the "assign_at" field.
func AssignAtIn(vs ...time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldIn(FieldAssignAt, vs...))
}

// AssignAtNotIn applies the NotIn predicate on the "assign_at" field.
func AssignAtNotIn(vs ...time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNotIn(FieldAssignAt, vs...))
}

// AssignAtGT applies the GT predicate on the "assign_at" field.
func AssignAtGT(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldGT(FieldAssignAt, v))
}

// AssignAtGTE applies the GTE predicate on the "assign_at" field.
func AssignAtGTE(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldGTE(FieldAssignAt, v))
}

// AssignAtLT applies the LT predicate on the "assign_at" field.
func AssignAtLT(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldLT(FieldAssignAt, v))
}

// AssignAtLTE applies the LTE predicate on the "assign_at" field.
func AssignAtLTE(v time.Time) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldLTE(FieldAssignAt, v))
}

// AssignAtIsNil applies the IsNil predicate on the "assign_at" field.
func AssignAtIsNil() predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldIsNull(FieldAssignAt))
}

// AssignAtNotNil applies the NotNil predicate on the "assign_at" field.
func AssignAtNotNil() predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNotNull(FieldAssignAt))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.FieldNotIn(FieldType, vs...))
}

// HasAssignedToUser applies the HasEdge predicate on the "assigned_to_user" edge.
func HasAssignedToUser() predicate.AlibabaCode {
	return predicate.AlibabaCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AssignedToUserTable, AssignedToUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedToUserWith applies the HasEdge predicate on the "assigned_to_user" edge with a given conditions (other predicates).
func HasAssignedToUserWith(preds ...predicate.User) predicate.AlibabaCode {
	return predicate.AlibabaCode(func(s *sql.Selector) {
		step := newAssignedToUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AlibabaCode) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AlibabaCode) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AlibabaCode) predicate.AlibabaCode {
	return predicate.AlibabaCode(sql.NotPredicates(p))
}
