// Code generated by ent, DO NOT EDIT.

package digikalacode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/espitman/jbm-hr-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldCode, v))
}

// Used applies equality check predicate on the "used" field. It's identical to UsedEQ.
func Used(v bool) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldUsed, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UsedByUserID applies equality check predicate on the "used_by_user_id" field. It's identical to UsedByUserIDEQ.
func UsedByUserID(v int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldUsedByUserID, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldUsedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldContainsFold(FieldCode, v))
}

// UsedEQ applies the EQ predicate on the "used" field.
func UsedEQ(v bool) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldUsed, v))
}

// UsedNEQ applies the NEQ predicate on the "used" field.
func UsedNEQ(v bool) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNEQ(FieldUsed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UsedByUserIDEQ applies the EQ predicate on the "used_by_user_id" field.
func UsedByUserIDEQ(v int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldUsedByUserID, v))
}

// UsedByUserIDNEQ applies the NEQ predicate on the "used_by_user_id" field.
func UsedByUserIDNEQ(v int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNEQ(FieldUsedByUserID, v))
}

// UsedByUserIDIn applies the In predicate on the "used_by_user_id" field.
func UsedByUserIDIn(vs ...int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldIn(FieldUsedByUserID, vs...))
}

// UsedByUserIDNotIn applies the NotIn predicate on the "used_by_user_id" field.
func UsedByUserIDNotIn(vs ...int) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNotIn(FieldUsedByUserID, vs...))
}

// UsedByUserIDIsNil applies the IsNil predicate on the "used_by_user_id" field.
func UsedByUserIDIsNil() predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldIsNull(FieldUsedByUserID))
}

// UsedByUserIDNotNil applies the NotNil predicate on the "used_by_user_id" field.
func UsedByUserIDNotNil() predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNotNull(FieldUsedByUserID))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.FieldNotNull(FieldUsedAt))
}

// HasUsedBy applies the HasEdge predicate on the "used_by" edge.
func HasUsedBy() predicate.DigikalaCode {
	return predicate.DigikalaCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsedByTable, UsedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsedByWith applies the HasEdge predicate on the "used_by" edge with a given conditions (other predicates).
func HasUsedByWith(preds ...predicate.User) predicate.DigikalaCode {
	return predicate.DigikalaCode(func(s *sql.Selector) {
		step := newUsedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DigikalaCode) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DigikalaCode) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DigikalaCode) predicate.DigikalaCode {
	return predicate.DigikalaCode(sql.NotPredicates(p))
}
