// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/espitman/jbm-hr-backend/ent/alibabacode"
	"github.com/espitman/jbm-hr-backend/ent/predicate"
	"github.com/espitman/jbm-hr-backend/ent/user"
)

// AlibabaCodeQuery is the builder for querying AlibabaCode entities.
type AlibabaCodeQuery struct {
	config
	ctx                *QueryContext
	order              []alibabacode.OrderOption
	inters             []Interceptor
	predicates         []predicate.AlibabaCode
	withAssignedToUser *UserQuery
	withFKs            bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AlibabaCodeQuery builder.
func (acq *AlibabaCodeQuery) Where(ps ...predicate.AlibabaCode) *AlibabaCodeQuery {
	acq.predicates = append(acq.predicates, ps...)
	return acq
}

// Limit the number of records to be returned by this query.
func (acq *AlibabaCodeQuery) Limit(limit int) *AlibabaCodeQuery {
	acq.ctx.Limit = &limit
	return acq
}

// Offset to start from.
func (acq *AlibabaCodeQuery) Offset(offset int) *AlibabaCodeQuery {
	acq.ctx.Offset = &offset
	return acq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (acq *AlibabaCodeQuery) Unique(unique bool) *AlibabaCodeQuery {
	acq.ctx.Unique = &unique
	return acq
}

// Order specifies how the records should be ordered.
func (acq *AlibabaCodeQuery) Order(o ...alibabacode.OrderOption) *AlibabaCodeQuery {
	acq.order = append(acq.order, o...)
	return acq
}

// QueryAssignedToUser chains the current query on the "assigned_to_user" edge.
func (acq *AlibabaCodeQuery) QueryAssignedToUser() *UserQuery {
	query := (&UserClient{config: acq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := acq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := acq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(alibabacode.Table, alibabacode.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, alibabacode.AssignedToUserTable, alibabacode.AssignedToUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(acq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AlibabaCode entity from the query.
// Returns a *NotFoundError when no AlibabaCode was found.
func (acq *AlibabaCodeQuery) First(ctx context.Context) (*AlibabaCode, error) {
	nodes, err := acq.Limit(1).All(setContextOp(ctx, acq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{alibabacode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (acq *AlibabaCodeQuery) FirstX(ctx context.Context) *AlibabaCode {
	node, err := acq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AlibabaCode ID from the query.
// Returns a *NotFoundError when no AlibabaCode ID was found.
func (acq *AlibabaCodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = acq.Limit(1).IDs(setContextOp(ctx, acq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{alibabacode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (acq *AlibabaCodeQuery) FirstIDX(ctx context.Context) int {
	id, err := acq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AlibabaCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AlibabaCode entity is found.
// Returns a *NotFoundError when no AlibabaCode entities are found.
func (acq *AlibabaCodeQuery) Only(ctx context.Context) (*AlibabaCode, error) {
	nodes, err := acq.Limit(2).All(setContextOp(ctx, acq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{alibabacode.Label}
	default:
		return nil, &NotSingularError{alibabacode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (acq *AlibabaCodeQuery) OnlyX(ctx context.Context) *AlibabaCode {
	node, err := acq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AlibabaCode ID in the query.
// Returns a *NotSingularError when more than one AlibabaCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (acq *AlibabaCodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = acq.Limit(2).IDs(setContextOp(ctx, acq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{alibabacode.Label}
	default:
		err = &NotSingularError{alibabacode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (acq *AlibabaCodeQuery) OnlyIDX(ctx context.Context) int {
	id, err := acq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AlibabaCodes.
func (acq *AlibabaCodeQuery) All(ctx context.Context) ([]*AlibabaCode, error) {
	ctx = setContextOp(ctx, acq.ctx, ent.OpQueryAll)
	if err := acq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AlibabaCode, *AlibabaCodeQuery]()
	return withInterceptors[[]*AlibabaCode](ctx, acq, qr, acq.inters)
}

// AllX is like All, but panics if an error occurs.
func (acq *AlibabaCodeQuery) AllX(ctx context.Context) []*AlibabaCode {
	nodes, err := acq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AlibabaCode IDs.
func (acq *AlibabaCodeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if acq.ctx.Unique == nil && acq.path != nil {
		acq.Unique(true)
	}
	ctx = setContextOp(ctx, acq.ctx, ent.OpQueryIDs)
	if err = acq.Select(alibabacode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (acq *AlibabaCodeQuery) IDsX(ctx context.Context) []int {
	ids, err := acq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (acq *AlibabaCodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, acq.ctx, ent.OpQueryCount)
	if err := acq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, acq, querierCount[*AlibabaCodeQuery](), acq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (acq *AlibabaCodeQuery) CountX(ctx context.Context) int {
	count, err := acq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (acq *AlibabaCodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, acq.ctx, ent.OpQueryExist)
	switch _, err := acq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (acq *AlibabaCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := acq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AlibabaCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (acq *AlibabaCodeQuery) Clone() *AlibabaCodeQuery {
	if acq == nil {
		return nil
	}
	return &AlibabaCodeQuery{
		config:             acq.config,
		ctx:                acq.ctx.Clone(),
		order:              append([]alibabacode.OrderOption{}, acq.order...),
		inters:             append([]Interceptor{}, acq.inters...),
		predicates:         append([]predicate.AlibabaCode{}, acq.predicates...),
		withAssignedToUser: acq.withAssignedToUser.Clone(),
		// clone intermediate query.
		sql:  acq.sql.Clone(),
		path: acq.path,
	}
}

// WithAssignedToUser tells the query-builder to eager-load the nodes that are connected to
// the "assigned_to_user" edge. The optional arguments are used to configure the query builder of the edge.
func (acq *AlibabaCodeQuery) WithAssignedToUser(opts ...func(*UserQuery)) *AlibabaCodeQuery {
	query := (&UserClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	acq.withAssignedToUser = query
	return acq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AlibabaCode.Query().
//		GroupBy(alibabacode.FieldCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (acq *AlibabaCodeQuery) GroupBy(field string, fields ...string) *AlibabaCodeGroupBy {
	acq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AlibabaCodeGroupBy{build: acq}
	grbuild.flds = &acq.ctx.Fields
	grbuild.label = alibabacode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//	}
//
//	client.AlibabaCode.Query().
//		Select(alibabacode.FieldCode).
//		Scan(ctx, &v)
func (acq *AlibabaCodeQuery) Select(fields ...string) *AlibabaCodeSelect {
	acq.ctx.Fields = append(acq.ctx.Fields, fields...)
	sbuild := &AlibabaCodeSelect{AlibabaCodeQuery: acq}
	sbuild.label = alibabacode.Label
	sbuild.flds, sbuild.scan = &acq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AlibabaCodeSelect configured with the given aggregations.
func (acq *AlibabaCodeQuery) Aggregate(fns ...AggregateFunc) *AlibabaCodeSelect {
	return acq.Select().Aggregate(fns...)
}

func (acq *AlibabaCodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range acq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, acq); err != nil {
				return err
			}
		}
	}
	for _, f := range acq.ctx.Fields {
		if !alibabacode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if acq.path != nil {
		prev, err := acq.path(ctx)
		if err != nil {
			return err
		}
		acq.sql = prev
	}
	return nil
}

func (acq *AlibabaCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AlibabaCode, error) {
	var (
		nodes       = []*AlibabaCode{}
		withFKs     = acq.withFKs
		_spec       = acq.querySpec()
		loadedTypes = [1]bool{
			acq.withAssignedToUser != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, alibabacode.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AlibabaCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AlibabaCode{config: acq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, acq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := acq.withAssignedToUser; query != nil {
		if err := acq.loadAssignedToUser(ctx, query, nodes, nil,
			func(n *AlibabaCode, e *User) { n.Edges.AssignedToUser = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (acq *AlibabaCodeQuery) loadAssignedToUser(ctx context.Context, query *UserQuery, nodes []*AlibabaCode, init func(*AlibabaCode), assign func(*AlibabaCode, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AlibabaCode)
	for i := range nodes {
		if nodes[i].AssignToUserID == nil {
			continue
		}
		fk := *nodes[i].AssignToUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "assign_to_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (acq *AlibabaCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := acq.querySpec()
	_spec.Node.Columns = acq.ctx.Fields
	if len(acq.ctx.Fields) > 0 {
		_spec.Unique = acq.ctx.Unique != nil && *acq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, acq.driver, _spec)
}

func (acq *AlibabaCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(alibabacode.Table, alibabacode.Columns, sqlgraph.NewFieldSpec(alibabacode.FieldID, field.TypeInt))
	_spec.From = acq.sql
	if unique := acq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if acq.path != nil {
		_spec.Unique = true
	}
	if fields := acq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alibabacode.FieldID)
		for i := range fields {
			if fields[i] != alibabacode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if acq.withAssignedToUser != nil {
			_spec.Node.AddColumnOnce(alibabacode.FieldAssignToUserID)
		}
	}
	if ps := acq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := acq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := acq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := acq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (acq *AlibabaCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(acq.driver.Dialect())
	t1 := builder.Table(alibabacode.Table)
	columns := acq.ctx.Fields
	if len(columns) == 0 {
		columns = alibabacode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if acq.sql != nil {
		selector = acq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if acq.ctx.Unique != nil && *acq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range acq.predicates {
		p(selector)
	}
	for _, p := range acq.order {
		p(selector)
	}
	if offset := acq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := acq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AlibabaCodeGroupBy is the group-by builder for AlibabaCode entities.
type AlibabaCodeGroupBy struct {
	selector
	build *AlibabaCodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (acgb *AlibabaCodeGroupBy) Aggregate(fns ...AggregateFunc) *AlibabaCodeGroupBy {
	acgb.fns = append(acgb.fns, fns...)
	return acgb
}

// Scan applies the selector query and scans the result into the given value.
func (acgb *AlibabaCodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acgb.build.ctx, ent.OpQueryGroupBy)
	if err := acgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlibabaCodeQuery, *AlibabaCodeGroupBy](ctx, acgb.build, acgb, acgb.build.inters, v)
}

func (acgb *AlibabaCodeGroupBy) sqlScan(ctx context.Context, root *AlibabaCodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(acgb.fns))
	for _, fn := range acgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*acgb.flds)+len(acgb.fns))
		for _, f := range *acgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*acgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AlibabaCodeSelect is the builder for selecting fields of AlibabaCode entities.
type AlibabaCodeSelect struct {
	*AlibabaCodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (acs *AlibabaCodeSelect) Aggregate(fns ...AggregateFunc) *AlibabaCodeSelect {
	acs.fns = append(acs.fns, fns...)
	return acs
}

// Scan applies the selector query and scans the result into the given value.
func (acs *AlibabaCodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acs.ctx, ent.OpQuerySelect)
	if err := acs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlibabaCodeQuery, *AlibabaCodeSelect](ctx, acs.AlibabaCodeQuery, acs, acs.inters, v)
}

func (acs *AlibabaCodeSelect) sqlScan(ctx context.Context, root *AlibabaCodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(acs.fns))
	for _, fn := range acs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*acs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
