// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/espitman/jbm-hr-backend/ent/alibabacode"
	"github.com/espitman/jbm-hr-backend/ent/predicate"
)

// AlibabaCodeDelete is the builder for deleting a AlibabaCode entity.
type AlibabaCodeDelete struct {
	config
	hooks    []Hook
	mutation *AlibabaCodeMutation
}

// Where appends a list predicates to the AlibabaCodeDelete builder.
func (acd *AlibabaCodeDelete) Where(ps ...predicate.AlibabaCode) *AlibabaCodeDelete {
	acd.mutation.Where(ps...)
	return acd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (acd *AlibabaCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, acd.sqlExec, acd.mutation, acd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (acd *AlibabaCodeDelete) ExecX(ctx context.Context) int {
	n, err := acd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (acd *AlibabaCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(alibabacode.Table, sqlgraph.NewFieldSpec(alibabacode.FieldID, field.TypeInt))
	if ps := acd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, acd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	acd.mutation.done = true
	return affected, err
}

// AlibabaCodeDeleteOne is the builder for deleting a single AlibabaCode entity.
type AlibabaCodeDeleteOne struct {
	acd *AlibabaCodeDelete
}

// Where appends a list predicates to the AlibabaCodeDelete builder.
func (acdo *AlibabaCodeDeleteOne) Where(ps ...predicate.AlibabaCode) *AlibabaCodeDeleteOne {
	acdo.acd.mutation.Where(ps...)
	return acdo
}

// Exec executes the deletion query.
func (acdo *AlibabaCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := acdo.acd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{alibabacode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (acdo *AlibabaCodeDeleteOne) ExecX(ctx context.Context) {
	if err := acdo.Exec(ctx); err != nil {
		panic(err)
	}
}
