// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/espitman/jbm-hr-backend/ent/digikalacode"
	"github.com/espitman/jbm-hr-backend/ent/predicate"
)

// DigikalaCodeDelete is the builder for deleting a DigikalaCode entity.
type DigikalaCodeDelete struct {
	config
	hooks    []Hook
	mutation *DigikalaCodeMutation
}

// Where appends a list predicates to the DigikalaCodeDelete builder.
func (dcd *DigikalaCodeDelete) Where(ps ...predicate.DigikalaCode) *DigikalaCodeDelete {
	dcd.mutation.Where(ps...)
	return dcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dcd *DigikalaCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dcd.sqlExec, dcd.mutation, dcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dcd *DigikalaCodeDelete) ExecX(ctx context.Context) int {
	n, err := dcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dcd *DigikalaCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(digikalacode.Table, sqlgraph.NewFieldSpec(digikalacode.FieldID, field.TypeInt))
	if ps := dcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dcd.mutation.done = true
	return affected, err
}

// DigikalaCodeDeleteOne is the builder for deleting a single DigikalaCode entity.
type DigikalaCodeDeleteOne struct {
	dcd *DigikalaCodeDelete
}

// Where appends a list predicates to the DigikalaCodeDelete builder.
func (dcdo *DigikalaCodeDeleteOne) Where(ps ...predicate.DigikalaCode) *DigikalaCodeDeleteOne {
	dcdo.dcd.mutation.Where(ps...)
	return dcdo
}

// Exec executes the deletion query.
func (dcdo *DigikalaCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := dcdo.dcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{digikalacode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dcdo *DigikalaCodeDeleteOne) ExecX(ctx context.Context) {
	if err := dcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
