// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/espitman/jbm-hr-backend/ent/hrteam"
	"github.com/espitman/jbm-hr-backend/ent/predicate"
)

// HRTeamQuery is the builder for querying HRTeam entities.
type HRTeamQuery struct {
	config
	ctx        *QueryContext
	order      []hrteam.OrderOption
	inters     []Interceptor
	predicates []predicate.HRTeam
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HRTeamQuery builder.
func (htq *HRTeamQuery) Where(ps ...predicate.HRTeam) *HRTeamQuery {
	htq.predicates = append(htq.predicates, ps...)
	return htq
}

// Limit the number of records to be returned by this query.
func (htq *HRTeamQuery) Limit(limit int) *HRTeamQuery {
	htq.ctx.Limit = &limit
	return htq
}

// Offset to start from.
func (htq *HRTeamQuery) Offset(offset int) *HRTeamQuery {
	htq.ctx.Offset = &offset
	return htq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (htq *HRTeamQuery) Unique(unique bool) *HRTeamQuery {
	htq.ctx.Unique = &unique
	return htq
}

// Order specifies how the records should be ordered.
func (htq *HRTeamQuery) Order(o ...hrteam.OrderOption) *HRTeamQuery {
	htq.order = append(htq.order, o...)
	return htq
}

// First returns the first HRTeam entity from the query.
// Returns a *NotFoundError when no HRTeam was found.
func (htq *HRTeamQuery) First(ctx context.Context) (*HRTeam, error) {
	nodes, err := htq.Limit(1).All(setContextOp(ctx, htq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hrteam.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (htq *HRTeamQuery) FirstX(ctx context.Context) *HRTeam {
	node, err := htq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HRTeam ID from the query.
// Returns a *NotFoundError when no HRTeam ID was found.
func (htq *HRTeamQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = htq.Limit(1).IDs(setContextOp(ctx, htq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hrteam.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (htq *HRTeamQuery) FirstIDX(ctx context.Context) int {
	id, err := htq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HRTeam entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HRTeam entity is found.
// Returns a *NotFoundError when no HRTeam entities are found.
func (htq *HRTeamQuery) Only(ctx context.Context) (*HRTeam, error) {
	nodes, err := htq.Limit(2).All(setContextOp(ctx, htq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hrteam.Label}
	default:
		return nil, &NotSingularError{hrteam.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (htq *HRTeamQuery) OnlyX(ctx context.Context) *HRTeam {
	node, err := htq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HRTeam ID in the query.
// Returns a *NotSingularError when more than one HRTeam ID is found.
// Returns a *NotFoundError when no entities are found.
func (htq *HRTeamQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = htq.Limit(2).IDs(setContextOp(ctx, htq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hrteam.Label}
	default:
		err = &NotSingularError{hrteam.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (htq *HRTeamQuery) OnlyIDX(ctx context.Context) int {
	id, err := htq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HRTeams.
func (htq *HRTeamQuery) All(ctx context.Context) ([]*HRTeam, error) {
	ctx = setContextOp(ctx, htq.ctx, ent.OpQueryAll)
	if err := htq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HRTeam, *HRTeamQuery]()
	return withInterceptors[[]*HRTeam](ctx, htq, qr, htq.inters)
}

// AllX is like All, but panics if an error occurs.
func (htq *HRTeamQuery) AllX(ctx context.Context) []*HRTeam {
	nodes, err := htq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HRTeam IDs.
func (htq *HRTeamQuery) IDs(ctx context.Context) (ids []int, err error) {
	if htq.ctx.Unique == nil && htq.path != nil {
		htq.Unique(true)
	}
	ctx = setContextOp(ctx, htq.ctx, ent.OpQueryIDs)
	if err = htq.Select(hrteam.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (htq *HRTeamQuery) IDsX(ctx context.Context) []int {
	ids, err := htq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (htq *HRTeamQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, htq.ctx, ent.OpQueryCount)
	if err := htq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, htq, querierCount[*HRTeamQuery](), htq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (htq *HRTeamQuery) CountX(ctx context.Context) int {
	count, err := htq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (htq *HRTeamQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, htq.ctx, ent.OpQueryExist)
	switch _, err := htq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (htq *HRTeamQuery) ExistX(ctx context.Context) bool {
	exist, err := htq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HRTeamQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (htq *HRTeamQuery) Clone() *HRTeamQuery {
	if htq == nil {
		return nil
	}
	return &HRTeamQuery{
		config:     htq.config,
		ctx:        htq.ctx.Clone(),
		order:      append([]hrteam.OrderOption{}, htq.order...),
		inters:     append([]Interceptor{}, htq.inters...),
		predicates: append([]predicate.HRTeam{}, htq.predicates...),
		// clone intermediate query.
		sql:  htq.sql.Clone(),
		path: htq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FullName string `json:"full_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HRTeam.Query().
//		GroupBy(hrteam.FieldFullName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (htq *HRTeamQuery) GroupBy(field string, fields ...string) *HRTeamGroupBy {
	htq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HRTeamGroupBy{build: htq}
	grbuild.flds = &htq.ctx.Fields
	grbuild.label = hrteam.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FullName string `json:"full_name,omitempty"`
//	}
//
//	client.HRTeam.Query().
//		Select(hrteam.FieldFullName).
//		Scan(ctx, &v)
func (htq *HRTeamQuery) Select(fields ...string) *HRTeamSelect {
	htq.ctx.Fields = append(htq.ctx.Fields, fields...)
	sbuild := &HRTeamSelect{HRTeamQuery: htq}
	sbuild.label = hrteam.Label
	sbuild.flds, sbuild.scan = &htq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HRTeamSelect configured with the given aggregations.
func (htq *HRTeamQuery) Aggregate(fns ...AggregateFunc) *HRTeamSelect {
	return htq.Select().Aggregate(fns...)
}

func (htq *HRTeamQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range htq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, htq); err != nil {
				return err
			}
		}
	}
	for _, f := range htq.ctx.Fields {
		if !hrteam.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if htq.path != nil {
		prev, err := htq.path(ctx)
		if err != nil {
			return err
		}
		htq.sql = prev
	}
	return nil
}

func (htq *HRTeamQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HRTeam, error) {
	var (
		nodes = []*HRTeam{}
		_spec = htq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HRTeam).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HRTeam{config: htq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, htq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (htq *HRTeamQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := htq.querySpec()
	_spec.Node.Columns = htq.ctx.Fields
	if len(htq.ctx.Fields) > 0 {
		_spec.Unique = htq.ctx.Unique != nil && *htq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, htq.driver, _spec)
}

func (htq *HRTeamQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hrteam.Table, hrteam.Columns, sqlgraph.NewFieldSpec(hrteam.FieldID, field.TypeInt))
	_spec.From = htq.sql
	if unique := htq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if htq.path != nil {
		_spec.Unique = true
	}
	if fields := htq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hrteam.FieldID)
		for i := range fields {
			if fields[i] != hrteam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := htq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := htq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := htq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := htq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (htq *HRTeamQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(htq.driver.Dialect())
	t1 := builder.Table(hrteam.Table)
	columns := htq.ctx.Fields
	if len(columns) == 0 {
		columns = hrteam.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if htq.sql != nil {
		selector = htq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if htq.ctx.Unique != nil && *htq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range htq.predicates {
		p(selector)
	}
	for _, p := range htq.order {
		p(selector)
	}
	if offset := htq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := htq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HRTeamGroupBy is the group-by builder for HRTeam entities.
type HRTeamGroupBy struct {
	selector
	build *HRTeamQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (htgb *HRTeamGroupBy) Aggregate(fns ...AggregateFunc) *HRTeamGroupBy {
	htgb.fns = append(htgb.fns, fns...)
	return htgb
}

// Scan applies the selector query and scans the result into the given value.
func (htgb *HRTeamGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, htgb.build.ctx, ent.OpQueryGroupBy)
	if err := htgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HRTeamQuery, *HRTeamGroupBy](ctx, htgb.build, htgb, htgb.build.inters, v)
}

func (htgb *HRTeamGroupBy) sqlScan(ctx context.Context, root *HRTeamQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(htgb.fns))
	for _, fn := range htgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*htgb.flds)+len(htgb.fns))
		for _, f := range *htgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*htgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := htgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HRTeamSelect is the builder for selecting fields of HRTeam entities.
type HRTeamSelect struct {
	*HRTeamQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hts *HRTeamSelect) Aggregate(fns ...AggregateFunc) *HRTeamSelect {
	hts.fns = append(hts.fns, fns...)
	return hts
}

// Scan applies the selector query and scans the result into the given value.
func (hts *HRTeamSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hts.ctx, ent.OpQuerySelect)
	if err := hts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HRTeamQuery, *HRTeamSelect](ctx, hts.HRTeamQuery, hts, hts.inters, v)
}

func (hts *HRTeamSelect) sqlScan(ctx context.Context, root *HRTeamQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hts.fns))
	for _, fn := range hts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
