// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/espitman/jbm-hr-backend/ent/request"
	"github.com/espitman/jbm-hr-backend/ent/requestmeta"
)

// RequestMetaCreate is the builder for creating a RequestMeta entity.
type RequestMetaCreate struct {
	config
	mutation *RequestMetaMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (rmc *RequestMetaCreate) SetRequestID(i int) *RequestMetaCreate {
	rmc.mutation.SetRequestID(i)
	return rmc
}

// SetKey sets the "key" field.
func (rmc *RequestMetaCreate) SetKey(s string) *RequestMetaCreate {
	rmc.mutation.SetKey(s)
	return rmc
}

// SetValue sets the "value" field.
func (rmc *RequestMetaCreate) SetValue(s string) *RequestMetaCreate {
	rmc.mutation.SetValue(s)
	return rmc
}

// SetRequest sets the "request" edge to the Request entity.
func (rmc *RequestMetaCreate) SetRequest(r *Request) *RequestMetaCreate {
	return rmc.SetRequestID(r.ID)
}

// Mutation returns the RequestMetaMutation object of the builder.
func (rmc *RequestMetaCreate) Mutation() *RequestMetaMutation {
	return rmc.mutation
}

// Save creates the RequestMeta in the database.
func (rmc *RequestMetaCreate) Save(ctx context.Context) (*RequestMeta, error) {
	return withHooks(ctx, rmc.sqlSave, rmc.mutation, rmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rmc *RequestMetaCreate) SaveX(ctx context.Context) *RequestMeta {
	v, err := rmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rmc *RequestMetaCreate) Exec(ctx context.Context) error {
	_, err := rmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rmc *RequestMetaCreate) ExecX(ctx context.Context) {
	if err := rmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rmc *RequestMetaCreate) check() error {
	if _, ok := rmc.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RequestMeta.request_id"`)}
	}
	if _, ok := rmc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "RequestMeta.key"`)}
	}
	if v, ok := rmc.mutation.Key(); ok {
		if err := requestmeta.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "RequestMeta.key": %w`, err)}
		}
	}
	if _, ok := rmc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "RequestMeta.value"`)}
	}
	if v, ok := rmc.mutation.Value(); ok {
		if err := requestmeta.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "RequestMeta.value": %w`, err)}
		}
	}
	if len(rmc.mutation.RequestIDs()) == 0 {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required edge "RequestMeta.request"`)}
	}
	return nil
}

func (rmc *RequestMetaCreate) sqlSave(ctx context.Context) (*RequestMeta, error) {
	if err := rmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rmc.mutation.id = &_node.ID
	rmc.mutation.done = true
	return _node, nil
}

func (rmc *RequestMetaCreate) createSpec() (*RequestMeta, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestMeta{config: rmc.config}
		_spec = sqlgraph.NewCreateSpec(requestmeta.Table, sqlgraph.NewFieldSpec(requestmeta.FieldID, field.TypeInt))
	)
	if value, ok := rmc.mutation.Key(); ok {
		_spec.SetField(requestmeta.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := rmc.mutation.Value(); ok {
		_spec.SetField(requestmeta.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if nodes := rmc.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestmeta.RequestTable,
			Columns: []string{requestmeta.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RequestMetaCreateBulk is the builder for creating many RequestMeta entities in bulk.
type RequestMetaCreateBulk struct {
	config
	err      error
	builders []*RequestMetaCreate
}

// Save creates the RequestMeta entities in the database.
func (rmcb *RequestMetaCreateBulk) Save(ctx context.Context) ([]*RequestMeta, error) {
	if rmcb.err != nil {
		return nil, rmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rmcb.builders))
	nodes := make([]*RequestMeta, len(rmcb.builders))
	mutators := make([]Mutator, len(rmcb.builders))
	for i := range rmcb.builders {
		func(i int, root context.Context) {
			builder := rmcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestMetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rmcb *RequestMetaCreateBulk) SaveX(ctx context.Context) []*RequestMeta {
	v, err := rmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rmcb *RequestMetaCreateBulk) Exec(ctx context.Context) error {
	_, err := rmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rmcb *RequestMetaCreateBulk) ExecX(ctx context.Context) {
	if err := rmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
