// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/espitman/jbm-hr-backend/ent/predicate"
	"github.com/espitman/jbm-hr-backend/ent/request"
	"github.com/espitman/jbm-hr-backend/ent/requestmeta"
)

// RequestMetaQuery is the builder for querying RequestMeta entities.
type RequestMetaQuery struct {
	config
	ctx         *QueryContext
	order       []requestmeta.OrderOption
	inters      []Interceptor
	predicates  []predicate.RequestMeta
	withRequest *RequestQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RequestMetaQuery builder.
func (rmq *RequestMetaQuery) Where(ps ...predicate.RequestMeta) *RequestMetaQuery {
	rmq.predicates = append(rmq.predicates, ps...)
	return rmq
}

// Limit the number of records to be returned by this query.
func (rmq *RequestMetaQuery) Limit(limit int) *RequestMetaQuery {
	rmq.ctx.Limit = &limit
	return rmq
}

// Offset to start from.
func (rmq *RequestMetaQuery) Offset(offset int) *RequestMetaQuery {
	rmq.ctx.Offset = &offset
	return rmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rmq *RequestMetaQuery) Unique(unique bool) *RequestMetaQuery {
	rmq.ctx.Unique = &unique
	return rmq
}

// Order specifies how the records should be ordered.
func (rmq *RequestMetaQuery) Order(o ...requestmeta.OrderOption) *RequestMetaQuery {
	rmq.order = append(rmq.order, o...)
	return rmq
}

// QueryRequest chains the current query on the "request" edge.
func (rmq *RequestMetaQuery) QueryRequest() *RequestQuery {
	query := (&RequestClient{config: rmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(requestmeta.Table, requestmeta.FieldID, selector),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, requestmeta.RequestTable, requestmeta.RequestColumn),
		)
		fromU = sqlgraph.SetNeighbors(rmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RequestMeta entity from the query.
// Returns a *NotFoundError when no RequestMeta was found.
func (rmq *RequestMetaQuery) First(ctx context.Context) (*RequestMeta, error) {
	nodes, err := rmq.Limit(1).All(setContextOp(ctx, rmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{requestmeta.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rmq *RequestMetaQuery) FirstX(ctx context.Context) *RequestMeta {
	node, err := rmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RequestMeta ID from the query.
// Returns a *NotFoundError when no RequestMeta ID was found.
func (rmq *RequestMetaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmq.Limit(1).IDs(setContextOp(ctx, rmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{requestmeta.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rmq *RequestMetaQuery) FirstIDX(ctx context.Context) int {
	id, err := rmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RequestMeta entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RequestMeta entity is found.
// Returns a *NotFoundError when no RequestMeta entities are found.
func (rmq *RequestMetaQuery) Only(ctx context.Context) (*RequestMeta, error) {
	nodes, err := rmq.Limit(2).All(setContextOp(ctx, rmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{requestmeta.Label}
	default:
		return nil, &NotSingularError{requestmeta.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rmq *RequestMetaQuery) OnlyX(ctx context.Context) *RequestMeta {
	node, err := rmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RequestMeta ID in the query.
// Returns a *NotSingularError when more than one RequestMeta ID is found.
// Returns a *NotFoundError when no entities are found.
func (rmq *RequestMetaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmq.Limit(2).IDs(setContextOp(ctx, rmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{requestmeta.Label}
	default:
		err = &NotSingularError{requestmeta.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rmq *RequestMetaQuery) OnlyIDX(ctx context.Context) int {
	id, err := rmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RequestMetaSlice.
func (rmq *RequestMetaQuery) All(ctx context.Context) ([]*RequestMeta, error) {
	ctx = setContextOp(ctx, rmq.ctx, ent.OpQueryAll)
	if err := rmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RequestMeta, *RequestMetaQuery]()
	return withInterceptors[[]*RequestMeta](ctx, rmq, qr, rmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rmq *RequestMetaQuery) AllX(ctx context.Context) []*RequestMeta {
	nodes, err := rmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RequestMeta IDs.
func (rmq *RequestMetaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rmq.ctx.Unique == nil && rmq.path != nil {
		rmq.Unique(true)
	}
	ctx = setContextOp(ctx, rmq.ctx, ent.OpQueryIDs)
	if err = rmq.Select(requestmeta.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rmq *RequestMetaQuery) IDsX(ctx context.Context) []int {
	ids, err := rmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rmq *RequestMetaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rmq.ctx, ent.OpQueryCount)
	if err := rmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rmq, querierCount[*RequestMetaQuery](), rmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rmq *RequestMetaQuery) CountX(ctx context.Context) int {
	count, err := rmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rmq *RequestMetaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rmq.ctx, ent.OpQueryExist)
	switch _, err := rmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rmq *RequestMetaQuery) ExistX(ctx context.Context) bool {
	exist, err := rmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RequestMetaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rmq *RequestMetaQuery) Clone() *RequestMetaQuery {
	if rmq == nil {
		return nil
	}
	return &RequestMetaQuery{
		config:      rmq.config,
		ctx:         rmq.ctx.Clone(),
		order:       append([]requestmeta.OrderOption{}, rmq.order...),
		inters:      append([]Interceptor{}, rmq.inters...),
		predicates:  append([]predicate.RequestMeta{}, rmq.predicates...),
		withRequest: rmq.withRequest.Clone(),
		// clone intermediate query.
		sql:  rmq.sql.Clone(),
		path: rmq.path,
	}
}

// WithRequest tells the query-builder to eager-load the nodes that are connected to
// the "request" edge. The optional arguments are used to configure the query builder of the edge.
func (rmq *RequestMetaQuery) WithRequest(opts ...func(*RequestQuery)) *RequestMetaQuery {
	query := (&RequestClient{config: rmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rmq.withRequest = query
	return rmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequestID int `json:"request_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RequestMeta.Query().
//		GroupBy(requestmeta.FieldRequestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rmq *RequestMetaQuery) GroupBy(field string, fields ...string) *RequestMetaGroupBy {
	rmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RequestMetaGroupBy{build: rmq}
	grbuild.flds = &rmq.ctx.Fields
	grbuild.label = requestmeta.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequestID int `json:"request_id,omitempty"`
//	}
//
//	client.RequestMeta.Query().
//		Select(requestmeta.FieldRequestID).
//		Scan(ctx, &v)
func (rmq *RequestMetaQuery) Select(fields ...string) *RequestMetaSelect {
	rmq.ctx.Fields = append(rmq.ctx.Fields, fields...)
	sbuild := &RequestMetaSelect{RequestMetaQuery: rmq}
	sbuild.label = requestmeta.Label
	sbuild.flds, sbuild.scan = &rmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RequestMetaSelect configured with the given aggregations.
func (rmq *RequestMetaQuery) Aggregate(fns ...AggregateFunc) *RequestMetaSelect {
	return rmq.Select().Aggregate(fns...)
}

func (rmq *RequestMetaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rmq); err != nil {
				return err
			}
		}
	}
	for _, f := range rmq.ctx.Fields {
		if !requestmeta.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rmq.path != nil {
		prev, err := rmq.path(ctx)
		if err != nil {
			return err
		}
		rmq.sql = prev
	}
	return nil
}

func (rmq *RequestMetaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RequestMeta, error) {
	var (
		nodes       = []*RequestMeta{}
		_spec       = rmq.querySpec()
		loadedTypes = [1]bool{
			rmq.withRequest != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RequestMeta).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RequestMeta{config: rmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rmq.withRequest; query != nil {
		if err := rmq.loadRequest(ctx, query, nodes, nil,
			func(n *RequestMeta, e *Request) { n.Edges.Request = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rmq *RequestMetaQuery) loadRequest(ctx context.Context, query *RequestQuery, nodes []*RequestMeta, init func(*RequestMeta), assign func(*RequestMeta, *Request)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RequestMeta)
	for i := range nodes {
		fk := nodes[i].RequestID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(request.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "request_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rmq *RequestMetaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rmq.querySpec()
	_spec.Node.Columns = rmq.ctx.Fields
	if len(rmq.ctx.Fields) > 0 {
		_spec.Unique = rmq.ctx.Unique != nil && *rmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rmq.driver, _spec)
}

func (rmq *RequestMetaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(requestmeta.Table, requestmeta.Columns, sqlgraph.NewFieldSpec(requestmeta.FieldID, field.TypeInt))
	_spec.From = rmq.sql
	if unique := rmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rmq.path != nil {
		_spec.Unique = true
	}
	if fields := rmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestmeta.FieldID)
		for i := range fields {
			if fields[i] != requestmeta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rmq.withRequest != nil {
			_spec.Node.AddColumnOnce(requestmeta.FieldRequestID)
		}
	}
	if ps := rmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rmq *RequestMetaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rmq.driver.Dialect())
	t1 := builder.Table(requestmeta.Table)
	columns := rmq.ctx.Fields
	if len(columns) == 0 {
		columns = requestmeta.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rmq.sql != nil {
		selector = rmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rmq.ctx.Unique != nil && *rmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rmq.predicates {
		p(selector)
	}
	for _, p := range rmq.order {
		p(selector)
	}
	if offset := rmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RequestMetaGroupBy is the group-by builder for RequestMeta entities.
type RequestMetaGroupBy struct {
	selector
	build *RequestMetaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rmgb *RequestMetaGroupBy) Aggregate(fns ...AggregateFunc) *RequestMetaGroupBy {
	rmgb.fns = append(rmgb.fns, fns...)
	return rmgb
}

// Scan applies the selector query and scans the result into the given value.
func (rmgb *RequestMetaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmgb.build.ctx, ent.OpQueryGroupBy)
	if err := rmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RequestMetaQuery, *RequestMetaGroupBy](ctx, rmgb.build, rmgb, rmgb.build.inters, v)
}

func (rmgb *RequestMetaGroupBy) sqlScan(ctx context.Context, root *RequestMetaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rmgb.fns))
	for _, fn := range rmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rmgb.flds)+len(rmgb.fns))
		for _, f := range *rmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RequestMetaSelect is the builder for selecting fields of RequestMeta entities.
type RequestMetaSelect struct {
	*RequestMetaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rms *RequestMetaSelect) Aggregate(fns ...AggregateFunc) *RequestMetaSelect {
	rms.fns = append(rms.fns, fns...)
	return rms
}

// Scan applies the selector query and scans the result into the given value.
func (rms *RequestMetaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rms.ctx, ent.OpQuerySelect)
	if err := rms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RequestMetaQuery, *RequestMetaSelect](ctx, rms.RequestMetaQuery, rms, rms.inters, v)
}

func (rms *RequestMetaSelect) sqlScan(ctx context.Context, root *RequestMetaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rms.fns))
	for _, fn := range rms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
