// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/espitman/jbm-hr-backend/ent/resume"
	"github.com/espitman/jbm-hr-backend/ent/user"
)

// Resume is the model entity for the Resume schema.
type Resume struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IntroducedName holds the value of the "introduced_name" field.
	IntroducedName string `json:"introduced_name,omitempty"`
	// IntroducedPhone holds the value of the "introduced_phone" field.
	IntroducedPhone string `json:"introduced_phone,omitempty"`
	// Position holds the value of the "position" field.
	Position string `json:"position,omitempty"`
	// File holds the value of the "file" field.
	File string `json:"file,omitempty"`
	// Status holds the value of the "status" field.
	Status resume.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResumeQuery when eager-loading is set.
	Edges        ResumeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResumeEdges holds the relations/edges for other nodes in the graph.
type ResumeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResumeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Resume) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resume.FieldID, resume.FieldUserID:
			values[i] = new(sql.NullInt64)
		case resume.FieldIntroducedName, resume.FieldIntroducedPhone, resume.FieldPosition, resume.FieldFile, resume.FieldStatus:
			values[i] = new(sql.NullString)
		case resume.FieldCreatedAt, resume.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Resume fields.
func (r *Resume) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resume.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case resume.FieldIntroducedName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field introduced_name", values[i])
			} else if value.Valid {
				r.IntroducedName = value.String
			}
		case resume.FieldIntroducedPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field introduced_phone", values[i])
			} else if value.Valid {
				r.IntroducedPhone = value.String
			}
		case resume.FieldPosition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				r.Position = value.String
			}
		case resume.FieldFile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file", values[i])
			} else if value.Valid {
				r.File = value.String
			}
		case resume.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				r.Status = resume.Status(value.String)
			}
		case resume.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		case resume.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				r.UpdatedAt = value.Time
			}
		case resume.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				r.UserID = int(value.Int64)
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Resume.
// This includes values selected through modifiers, order, etc.
func (r *Resume) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Resume entity.
func (r *Resume) QueryUser() *UserQuery {
	return NewResumeClient(r.config).QueryUser(r)
}

// Update returns a builder for updating this Resume.
// Note that you need to call Resume.Unwrap() before calling this method if this Resume
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Resume) Update() *ResumeUpdateOne {
	return NewResumeClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Resume entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Resume) Unwrap() *Resume {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Resume is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Resume) String() string {
	var builder strings.Builder
	builder.WriteString("Resume(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("introduced_name=")
	builder.WriteString(r.IntroducedName)
	builder.WriteString(", ")
	builder.WriteString("introduced_phone=")
	builder.WriteString(r.IntroducedPhone)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(r.Position)
	builder.WriteString(", ")
	builder.WriteString("file=")
	builder.WriteString(r.File)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", r.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(r.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", r.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// Resumes is a parsable slice of Resume.
type Resumes []*Resume
