// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/espitman/jbm-hr-backend/ent/album"
	"github.com/espitman/jbm-hr-backend/ent/department"
	"github.com/espitman/jbm-hr-backend/ent/otp"
	"github.com/espitman/jbm-hr-backend/ent/schema"
	"github.com/espitman/jbm-hr-backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	albumFields := schema.Album{}.Fields()
	_ = albumFields
	// albumDescURL is the schema descriptor for url field.
	albumDescURL := albumFields[0].Descriptor()
	// album.URLValidator is a validator for the "url" field. It is called by the builders before save.
	album.URLValidator = albumDescURL.Validators[0].(func(string) error)
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescTitle is the schema descriptor for title field.
	departmentDescTitle := departmentFields[0].Descriptor()
	// department.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	department.TitleValidator = departmentDescTitle.Validators[0].(func(string) error)
	// departmentDescDescription is the schema descriptor for description field.
	departmentDescDescription := departmentFields[1].Descriptor()
	// department.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	department.DescriptionValidator = departmentDescDescription.Validators[0].(func(string) error)
	// departmentDescImage is the schema descriptor for image field.
	departmentDescImage := departmentFields[2].Descriptor()
	// department.ImageValidator is a validator for the "image" field. It is called by the builders before save.
	department.ImageValidator = departmentDescImage.Validators[0].(func(string) error)
	// departmentDescIcon is the schema descriptor for icon field.
	departmentDescIcon := departmentFields[3].Descriptor()
	// department.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	department.IconValidator = departmentDescIcon.Validators[0].(func(string) error)
	// departmentDescColor is the schema descriptor for color field.
	departmentDescColor := departmentFields[4].Descriptor()
	// department.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	department.ColorValidator = departmentDescColor.Validators[0].(func(string) error)
	// departmentDescShortName is the schema descriptor for shortName field.
	departmentDescShortName := departmentFields[5].Descriptor()
	// department.ShortNameValidator is a validator for the "shortName" field. It is called by the builders before save.
	department.ShortNameValidator = departmentDescShortName.Validators[0].(func(string) error)
	otpFields := schema.OTP{}.Fields()
	_ = otpFields
	// otpDescCode is the schema descriptor for code field.
	otpDescCode := otpFields[0].Descriptor()
	// otp.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	otp.CodeValidator = otpDescCode.Validators[0].(func(string) error)
	// otpDescExpiresAt is the schema descriptor for expires_at field.
	otpDescExpiresAt := otpFields[1].Descriptor()
	// otp.DefaultExpiresAt holds the default value on creation for the expires_at field.
	otp.DefaultExpiresAt = otpDescExpiresAt.Default.(func() time.Time)
	// otp.UpdateDefaultExpiresAt holds the default value on update for the expires_at field.
	otp.UpdateDefaultExpiresAt = otpDescExpiresAt.UpdateDefault.(func() time.Time)
	// otpDescUsed is the schema descriptor for used field.
	otpDescUsed := otpFields[2].Descriptor()
	// otp.DefaultUsed holds the default value on creation for the used field.
	otp.DefaultUsed = otpDescUsed.Default.(bool)
	// otpDescCreatedAt is the schema descriptor for created_at field.
	otpDescCreatedAt := otpFields[3].Descriptor()
	// otp.DefaultCreatedAt holds the default value on creation for the created_at field.
	otp.DefaultCreatedAt = otpDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[1].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[2].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[3].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
}
