// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/espitman/jbm-hr-backend/ent/album"
	"github.com/espitman/jbm-hr-backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	albumFields := schema.Album{}.Fields()
	_ = albumFields
	// albumDescURL is the schema descriptor for url field.
	albumDescURL := albumFields[0].Descriptor()
	// album.URLValidator is a validator for the "url" field. It is called by the builders before save.
	album.URLValidator = albumDescURL.Validators[0].(func(string) error)
}
