// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldFullName holds the string denoting the full_name field in the database.
	FieldFullName = "full_name"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldPersonnelNumber holds the string denoting the personnel_number field in the database.
	FieldPersonnelNumber = "personnel_number"
	// FieldNationalCode holds the string denoting the national_code field in the database.
	FieldNationalCode = "national_code"
	// FieldBirthdate holds the string denoting the birthdate field in the database.
	FieldBirthdate = "birthdate"
	// FieldCooperationStartDate holds the string denoting the cooperation_start_date field in the database.
	FieldCooperationStartDate = "cooperation_start_date"
	// FieldConfirmed holds the string denoting the confirmed field in the database.
	FieldConfirmed = "confirmed"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// EdgeOtps holds the string denoting the otps edge name in mutations.
	EdgeOtps = "otps"
	// EdgeResumes holds the string denoting the resumes edge name in mutations.
	EdgeResumes = "resumes"
	// EdgeRequests holds the string denoting the requests edge name in mutations.
	EdgeRequests = "requests"
	// EdgeDepartment holds the string denoting the department edge name in mutations.
	EdgeDepartment = "department"
	// EdgeDigikalaCodes holds the string denoting the digikala_codes edge name in mutations.
	EdgeDigikalaCodes = "digikala_codes"
	// EdgeAlibabaCodes holds the string denoting the alibaba_codes edge name in mutations.
	EdgeAlibabaCodes = "alibaba_codes"
	// Table holds the table name of the user in the database.
	Table = "users"
	// OtpsTable is the table that holds the otps relation/edge.
	OtpsTable = "ot_ps"
	// OtpsInverseTable is the table name for the OTP entity.
	// It exists in this package in order to avoid circular dependency with the "otp" package.
	OtpsInverseTable = "ot_ps"
	// OtpsColumn is the table column denoting the otps relation/edge.
	OtpsColumn = "user_otps"
	// ResumesTable is the table that holds the resumes relation/edge.
	ResumesTable = "resumes"
	// ResumesInverseTable is the table name for the Resume entity.
	// It exists in this package in order to avoid circular dependency with the "resume" package.
	ResumesInverseTable = "resumes"
	// ResumesColumn is the table column denoting the resumes relation/edge.
	ResumesColumn = "user_id"
	// RequestsTable is the table that holds the requests relation/edge.
	RequestsTable = "requests"
	// RequestsInverseTable is the table name for the Request entity.
	// It exists in this package in order to avoid circular dependency with the "request" package.
	RequestsInverseTable = "requests"
	// RequestsColumn is the table column denoting the requests relation/edge.
	RequestsColumn = "user_id"
	// DepartmentTable is the table that holds the department relation/edge.
	DepartmentTable = "users"
	// DepartmentInverseTable is the table name for the Department entity.
	// It exists in this package in order to avoid circular dependency with the "department" package.
	DepartmentInverseTable = "departments"
	// DepartmentColumn is the table column denoting the department relation/edge.
	DepartmentColumn = "department_users"
	// DigikalaCodesTable is the table that holds the digikala_codes relation/edge.
	DigikalaCodesTable = "digikala_codes"
	// DigikalaCodesInverseTable is the table name for the DigikalaCode entity.
	// It exists in this package in order to avoid circular dependency with the "digikalacode" package.
	DigikalaCodesInverseTable = "digikala_codes"
	// DigikalaCodesColumn is the table column denoting the digikala_codes relation/edge.
	DigikalaCodesColumn = "assign_to_user_id"
	// AlibabaCodesTable is the table that holds the alibaba_codes relation/edge.
	AlibabaCodesTable = "alibaba_codes"
	// AlibabaCodesInverseTable is the table name for the AlibabaCode entity.
	// It exists in this package in order to avoid circular dependency with the "alibabacode" package.
	AlibabaCodesInverseTable = "alibaba_codes"
	// AlibabaCodesColumn is the table column denoting the alibaba_codes relation/edge.
	AlibabaCodesColumn = "user_alibaba_codes"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPhone,
	FieldFirstName,
	FieldLastName,
	FieldFullName,
	FieldRole,
	FieldAvatar,
	FieldPassword,
	FieldPersonnelNumber,
	FieldNationalCode,
	FieldBirthdate,
	FieldCooperationStartDate,
	FieldConfirmed,
	FieldActive,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "users"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"department_users",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	FirstNameValidator func(string) error
	// LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	LastNameValidator func(string) error
	// FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	FullNameValidator func(string) error
	// PersonnelNumberValidator is a validator for the "personnel_number" field. It is called by the builders before save.
	PersonnelNumberValidator func(string) error
	// NationalCodeValidator is a validator for the "national_code" field. It is called by the builders before save.
	NationalCodeValidator func(string) error
	// DefaultConfirmed holds the default value on creation for the "confirmed" field.
	DefaultConfirmed bool
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
)

// Role defines the type for the "role" enum field.
type Role string

// RoleEmployee is the default value of the Role enum.
const DefaultRole = RoleEmployee

// Role values.
const (
	RoleAdmin    Role = "admin"
	RoleEmployee Role = "employee"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleAdmin, RoleEmployee:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByFirstName orders the results by the first_name field.
func ByFirstName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstName, opts...).ToFunc()
}

// ByLastName orders the results by the last_name field.
func ByLastName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastName, opts...).ToFunc()
}

// ByFullName orders the results by the full_name field.
func ByFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullName, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByAvatar orders the results by the avatar field.
func ByAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatar, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByPersonnelNumber orders the results by the personnel_number field.
func ByPersonnelNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPersonnelNumber, opts...).ToFunc()
}

// ByNationalCode orders the results by the national_code field.
func ByNationalCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNationalCode, opts...).ToFunc()
}

// ByBirthdate orders the results by the birthdate field.
func ByBirthdate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBirthdate, opts...).ToFunc()
}

// ByCooperationStartDate orders the results by the cooperation_start_date field.
func ByCooperationStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooperationStartDate, opts...).ToFunc()
}

// ByConfirmed orders the results by the confirmed field.
func ByConfirmed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmed, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByOtpsCount orders the results by otps count.
func ByOtpsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOtpsStep(), opts...)
	}
}

// ByOtps orders the results by otps terms.
func ByOtps(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOtpsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByResumesCount orders the results by resumes count.
func ByResumesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResumesStep(), opts...)
	}
}

// ByResumes orders the results by resumes terms.
func ByResumes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResumesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRequestsCount orders the results by requests count.
func ByRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequestsStep(), opts...)
	}
}

// ByRequests orders the results by requests terms.
func ByRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDepartmentField orders the results by department field.
func ByDepartmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDepartmentStep(), sql.OrderByField(field, opts...))
	}
}

// ByDigikalaCodesCount orders the results by digikala_codes count.
func ByDigikalaCodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDigikalaCodesStep(), opts...)
	}
}

// ByDigikalaCodes orders the results by digikala_codes terms.
func ByDigikalaCodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDigikalaCodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAlibabaCodesCount orders the results by alibaba_codes count.
func ByAlibabaCodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAlibabaCodesStep(), opts...)
	}
}

// ByAlibabaCodes orders the results by alibaba_codes terms.
func ByAlibabaCodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAlibabaCodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOtpsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OtpsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OtpsTable, OtpsColumn),
	)
}
func newResumesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResumesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResumesTable, ResumesColumn),
	)
}
func newRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RequestsTable, RequestsColumn),
	)
}
func newDepartmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DepartmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
	)
}
func newDigikalaCodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DigikalaCodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DigikalaCodesTable, DigikalaCodesColumn),
	)
}
func newAlibabaCodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AlibabaCodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AlibabaCodesTable, AlibabaCodesColumn),
	)
}
