// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Album is the predicate function for album builders.
type Album func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// HRTeam is the predicate function for hrteam builders.
type HRTeam func(*sql.Selector)

// OTP is the predicate function for otp builders.
type OTP func(*sql.Selector)

// Request is the predicate function for request builders.
type Request func(*sql.Selector)

// RequestMeta is the predicate function for requestmeta builders.
type RequestMeta func(*sql.Selector)

// Resume is the predicate function for resume builders.
type Resume func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
